port: 80
storage:
  home: 'C:\88\me'
  private: 'C:\88\private'
  items: 'C:\88\items'
  dats: 'C:\88\dat'
  wiki: 'C:\88\wiki'
windows:
  index:
    openDevTools: true
    file: "electron.html"
    maximize: true
    BrowserWindow:
      icon: "logo.ico"
      frame: false
      show: false
      titleBarStyle: "hiddenInset"
      width: 1800
      height: 300
      useContentSize: true
      title: "Pix8"
      webPreferences:
        plugins: true
        blinkFeatures: "OverlayScrollbars"
